name: Kotlin CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Kotlin compiler
      run: sudo snap install --classic kotlin

    - name: Compile Kotlin code
      run: |
        # 创建输出目录
        mkdir -p out
        # 生成带运行时的可执行 JAR
        kotlinc src/**/*.kt -include-runtime -d out/app-full.jar

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kotlin-build
        path: ./out/*.jar
